package co.edu.unicauca.DesingPatterns.domain.entities;

public enum EnumTipoAccion {
    
    // FASE 1 - FORMULARIO A
    PRESENTAR_FORMATO_A,
    EVALUAR_COMITE,
    SOLICITAR_CORRECCIONES_COMITE,
    APROBAR_COMITE,
    RECHAZAR_COMITE,
    CORREGIR_FORMATO_A,

    // FASE 2 - ANTEPROYECTO  
    INICIAR_ANTEPROYECTO,
    PRESENTAR_ANTEPROYECTO,
    EVALUAR_DEPARTAMENTO,
    SOLICITAR_CORRECCIONES_DEPARTAMENTO,
    APROBAR_DEPARTAMENTO,
    RECHAZAR_DEPARTAMENTO,

    // FASE 3 - CONSEJO
    APROBAR_CONSEJO,
    EMITIR_RESOLUCION,

    // FASE 4 - DESARROLLO
    INICIAR_DESARROLLO,
    SOLICITAR_PRORROGA,
    FINALIZAR_MONOGRAFIA,

    // FASE 5 - SUSTENTACIÓN
    PRESENTAR_DECANATURA,
    ASIGNAR_FECHA_SUSTENTACION,
    REALIZAR_SUSTENTACION,
    APROBAR_SUSTENTACION,
    RECHAZAR_SUSTENTACION
    
}
